/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as IncidentsIdCommandRouteImport } from './routes/incidents.$id_.command'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdCommandRoute = IncidentsIdCommandRouteImport.update({
  id: '/incidents/$id_/command',
  path: '/incidents/$id/command',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/detect': typeof DetectRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/drift': typeof DriftRoute
  '/history': typeof HistoryRouteWithChildren
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/response': typeof ResponseRoute
  '/settings': typeof SettingsRoute
  '/what-if': typeof WhatIfRoute
  '/history/$id': typeof HistoryIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/incidents/$id/command': typeof IncidentsIdCommandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/detect': typeof DetectRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/drift': typeof DriftRoute
  '/history': typeof HistoryRouteWithChildren
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/response': typeof ResponseRoute
  '/settings': typeof SettingsRoute
  '/what-if': typeof WhatIfRoute
  '/history/$id': typeof HistoryIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/incidents': typeof IncidentsIndexRoute
  '/incidents/$id/command': typeof IncidentsIdCommandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/detect': typeof DetectRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/drift': typeof DriftRoute
  '/history': typeof HistoryRouteWithChildren
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/response': typeof ResponseRoute
  '/settings': typeof SettingsRoute
  '/what-if': typeof WhatIfRoute
  '/history/$id': typeof HistoryIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/incidents/$id_/command': typeof IncidentsIdCommandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/detect'
    | '/digital-twin'
    | '/drift'
    | '/history'
    | '/impact'
    | '/login'
    | '/register'
    | '/reports'
    | '/response'
    | '/settings'
    | '/what-if'
    | '/history/$id'
    | '/incidents/$id'
    | '/onboarding/role'
    | '/incidents/'
    | '/incidents/$id/command'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/detect'
    | '/digital-twin'
    | '/drift'
    | '/history'
    | '/impact'
    | '/login'
    | '/register'
    | '/reports'
    | '/response'
    | '/settings'
    | '/what-if'
    | '/history/$id'
    | '/incidents/$id'
    | '/onboarding/role'
    | '/incidents'
    | '/incidents/$id/command'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/detect'
    | '/digital-twin'
    | '/drift'
    | '/history'
    | '/impact'
    | '/login'
    | '/register'
    | '/reports'
    | '/response'
    | '/settings'
    | '/what-if'
    | '/history/$id'
    | '/incidents/$id'
    | '/onboarding/role'
    | '/incidents/'
    | '/incidents/$id_/command'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DetectRoute: typeof DetectRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  DriftRoute: typeof DriftRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResponseRoute: typeof ResponseRoute
  SettingsRoute: typeof SettingsRoute
  WhatIfRoute: typeof WhatIfRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  IncidentsIdCommandRoute: typeof IncidentsIdCommandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id_/command': {
      id: '/incidents/$id_/command'
      path: '/incidents/$id/command'
      fullPath: '/incidents/$id/command'
      preLoaderRoute: typeof IncidentsIdCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DetectRoute: DetectRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  DriftRoute: DriftRoute,
  HistoryRoute: HistoryRouteWithChildren,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResponseRoute: ResponseRoute,
  SettingsRoute: SettingsRoute,
  WhatIfRoute: WhatIfRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  IncidentsIdCommandRoute: IncidentsIdCommandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
